# Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by the Apache v2 license that can be found in the
# LICENSE file.

[project]
name = "git-maruel"
version = "0.0.0"
requires-python = ">=3.12"

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pylint."messages control"]
disable = [
  "line-too-long",
  "missing-module-docstring",
  "too-many-arguments",
  "too-many-branches",
  "too-many-locals",
  "too-many-positional-arguments",
  "too-many-return-statements",
  "too-many-statements",
]
